### ISSUE TITLE
django CMS 4.0 

### ISSUE THREAD

**Issue by logicnextPramod** [divio/djangocms-versioning#161]
django CMS Versioning requires that you have a django CMS 4.0 (or higher).
Where is 4.0?

**Comment by chaosk** [comment]
Hello!

Both this addon and CMS 4.0 are currently under heavy development. I cannot give any estimates as to when versioning receives a public release at the moment.

**Comment by jedie** [comment]
IMHO a good Question... Where can more information be found?

...and what's with djangocms-history ?
See: https://github.com/divio/djangocms-history/issues/28
